// CERBERUS/RECOVERY domain (slots 151-200): cerberus/core, policy, artifact-trust, integrations.
// Hash literals are computed here with node:crypto directly, never with the code under test.
import { createHash } from "node:crypto";

const DEC = "cerberus/core/decide.ts";
const NORM = "cerberus/core/normalize.ts";
const POL = "cerberus/policy/policy.ts";
const TRUST = "cerberus/artifact-trust/artifact-trust.ts";
const ADP = "cerberus/integrations/verdict-adapters.ts";
const sha = (/** @type {any} */ s) => createHash("sha256").update(Buffer.from(s, "utf8")).digest("hex");
const H = sha("hello");
const ART = { name: "a.txt", content: "hello", sha256: H };
const VALID = { action: "detect", toepara: "ADMITTED", trustGate: "AUTHORIZED", artifact: ART };
const brief = (/** @type {any} */ r) => ({ decision: r.decision, reasons: r.reasons });
const ADM = (/** @type {any} */ v) => ({ name: "a", verdict: () => v });
const GOOD = { toepara: ADM("ADMITTED"), trustGate: ADM("AUTHORIZED") };
const ALL_PASS = { input: "PASS", policy: "PASS", toepara: "PASS", trustGate: "PASS", artifactTrust: "PASS" };

/** @type {import("../types.d.ts").Spec[]} */
export const SPECS = [
  { slot: 151, target: DEC, expected: { decision: "PROCEED", reasons: [], verdictSource: "caller-supplied", stages: ALL_PASS },
    run: (m) => { const r = m.decide(VALID); return { decision: r.decision, reasons: r.reasons, verdictSource: r.verdictSource, stages: r.stages }; },
    claim: "fully valid evidence yields PROCEED, no reasons, all five stages PASS, source caller-supplied" },
  { slot: 152, target: DEC, expected: { nestedAndTopKeyOrderIrrelevant: true, swappedVerdictsDifferentDigest: true, valuesNotSortedAway: true },
    run: (m) => { const reordered = { artifact: { sha256: H, content: "hello", name: "a.txt" }, trustGate: "AUTHORIZED", toepara: "ADMITTED", action: "detect" }; const swapped = { ...VALID, toepara: "AUTHORIZED", trustGate: "ADMITTED" }; return { nestedAndTopKeyOrderIrrelevant: m.decide(VALID).receiptDigest === m.decide(reordered).receiptDigest, swappedVerdictsDifferentDigest: m.decide(VALID).inputDigest !== m.decide(swapped).inputDigest, valuesNotSortedAway: m.decide(VALID).receiptDigest !== m.decide(swapped).receiptDigest }; },
    claim: "key order (top-level and nested) never changes the receipt digest, but swapping the toepara/trustGate VALUES does - canonicalisation sorts keys, not values" },
  { slot: 153, target: DEC, expected: { inputDigestDiffers: true, receiptDigestDiffers: true },
    run: (m) => { const other = { ...VALID, artifact: { name: "a.txt", content: "bye", sha256: sha("bye") } }; const a = m.decide(VALID); const b = m.decide(other); return { inputDigestDiffers: a.inputDigest !== b.inputDigest, receiptDigestDiffers: a.receiptDigest !== b.receiptDigest }; },
    claim: "a different (still valid) artifact changes both the input digest and the receipt digest" },
  { slot: 154, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["artifact-missing"], artifactTrust: "FAIL" },
    run: (m) => { const r = m.decide({ action: "detect", toepara: "ADMITTED", trustGate: "AUTHORIZED" }); return { ...brief(r), artifactTrust: r.stages.artifactTrust }; },
    claim: "no artifact at all fails closed with exactly artifact-missing" },
  { slot: 155, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["artifact-digest-mismatch"], declared: H, computed: sha("hellO") },
    run: (m) => { const r = m.decide({ ...VALID, artifact: { ...ART, content: "hellO" } }); return { ...brief(r), declared: r.evidence.artifact.declaredSha256, computed: r.evidence.artifact.computedSha256 }; },
    claim: "content edited after hashing fails closed and the receipt shows declared != computed digest" },
  { slot: 156, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["artifact-digest-malformed"] },
    run: (m) => brief(m.decide({ ...VALID, artifact: { ...ART, sha256: H.toUpperCase() } })),
    claim: "an upper-case hex digest is malformed (lowercase hex required), even though it is the right hash" },
  { slot: 157, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["toepara-not-admitted"], stages: { input: "PASS", policy: "PASS", toepara: "FAIL", trustGate: "PASS", artifactTrust: "PASS" } },
    run: (m) => { const r = m.decide({ ...VALID, toepara: "REJECTED" }); return { ...brief(r), stages: r.stages }; },
    claim: "TOEPARA not admitted fails exactly the toepara stage and nothing else" },
  { slot: 158, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["trust-gate-not-authorized"], stages: { input: "PASS", policy: "PASS", toepara: "PASS", trustGate: "FAIL", artifactTrust: "PASS" } },
    run: (m) => { const r = m.decide({ ...VALID, trustGate: "DENIED" }); return { ...brief(r), stages: r.stages }; },
    claim: "Trust Gate not authorized fails exactly the trustGate stage and nothing else" },
  { slot: 159, target: DEC, expected: { merge: ["policy-action-denied"], deploy: ["policy-action-denied"], authorize: ["policy-action-denied"] },
    run: (m) => ({ merge: m.decide({ ...VALID, action: "merge" }).reasons, deploy: m.decide({ ...VALID, action: "deploy" }).reasons, authorize: m.decide({ ...VALID, action: "authorize" }).reasons }),
    claim: "merge, deploy and authorize are denied by policy even when every piece of evidence is valid" },
  { slot: 160, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["policy-action-denied"], evidenceAction: null },
    run: (m) => { const r = m.decide({ ...VALID, action: 10n }); return { ...brief(r), evidenceAction: r.evidence.action }; },
    claim: "a BigInt where a string belongs denies (no throw) and is recorded as null evidence" },
  { slot: 161, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["input-accessor-property"], stages: { input: "FAIL", policy: "NOT_EVALUATED", toepara: "NOT_EVALUATED", trustGate: "NOT_EVALUATED", artifactTrust: "NOT_EVALUATED" } },
    run: (m) => { const o = { ...VALID }; Object.defineProperty(o, "action", { enumerable: true, get: () => "detect" }); const r = m.decide(o); return { ...brief(r), stages: r.stages }; },
    claim: "a getter-backed field is rejected at the input stage; later stages are NOT_EVALUATED" },
  { slot: 162, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["input-not-plain-object"] },
    run: (m) => brief(m.decide(Object.create({ ...VALID }))), claim: "an object whose verdicts live only on its prototype is not a plain object and is denied" },
  { slot: 163, target: DEC, expected: { decision: "FAIL_CLOSED", reasons: ["toepara-not-admitted", "trust-gate-not-authorized"] },
    run: (m) => { const proto = /** @type {any} */ (Object.prototype); proto.toepara = "ADMITTED"; proto.trustGate = "AUTHORIZED"; try { return brief(m.decide({ action: "detect", artifact: ART })); } finally { delete proto.toepara; delete proto.trustGate; } },
    claim: "a polluted Object.prototype cannot supply TOEPARA / Trust Gate verdicts" },
  { slot: 164, target: DEC, expected: { equal: true, decision: "PROCEED" },
    run: (m) => { const np = Object.assign(Object.create(null), VALID); return { equal: m.decide(np).receiptDigest === m.decide(VALID).receiptDigest, decision: m.decide(np).decision }; },
    claim: "a null-prototype plain object is accepted and produces the same receipt digest as an ordinary one" },
  { slot: 165, target: DEC, expected: { sameDigest: true },
    run: (m) => { const cyc = {}; cyc.self = cyc; return { sameDigest: m.decide({ ...VALID, junk: cyc, big: 1n }).receiptDigest === m.decide(VALID).receiptDigest }; },
    claim: "unknown extra keys (cyclic, BigInt) are never read and do not change the receipt" },
  { slot: 166, target: DEC, expected: ["FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED"],
    run: (m) => ["admitted", "ADMITTED ", " ADMITTED", "ADMITTED\n", "", true].map((v) => m.decide({ ...VALID, toepara: v }).decision),
    claim: "case, whitespace, empty and boolean variants of ADMITTED never pass the TOEPARA stage" },
  { slot: 167, target: DEC, expected: ["FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED"],
    run: (m) => ["authorized", "AUTHORIZED ", "Authorized", "ADMITTED"].map((v) => m.decide({ ...VALID, trustGate: v }).decision),
    claim: "case, whitespace and wrong-vocabulary variants of AUTHORIZED never pass the Trust Gate stage" },
  { slot: 168, target: DEC, expected: ["FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED", "FAIL_CLOSED"],
    run: (m) => ["DETECT", "detect ", "Detect", "", "detect\0", 5].map((v) => m.decide({ ...VALID, action: v }).decision),
    claim: "case/whitespace/NUL variants of an allowed action and non-strings are all denied by policy" },
  { slot: 169, target: DEC, expected: { detect: "PROCEED", recover: "PROCEED", recommend: "PROCEED" },
    run: (m) => Object.fromEntries(["detect", "recover", "recommend"].map((a) => [a, m.decide({ ...VALID, action: a }).decision])),
    claim: "exactly the three allowed actions proceed with valid evidence" },
  { slot: 170, target: DEC, expected: [["artifact-missing"], ["artifact-missing"], ["artifact-missing"], ["artifact-missing"]],
    run: (m) => ["x", [ART], null, 42].map((a) => m.decide({ ...VALID, artifact: a }).reasons),
    claim: "an artifact that is a string, array, null or number is treated as missing" },
  { slot: 171, target: TRUST, expected: { noName: "artifact-name-invalid", noContent: "artifact-content-invalid", shortDigest: "artifact-digest-malformed", notObject: "artifact-missing" },
    run: (m) => ({ noName: m.artifactTrustFailure({ ...ART, name: "" }), noContent: m.artifactTrustFailure({ name: "a", sha256: H }), shortDigest: m.artifactTrustFailure({ ...ART, sha256: "abc" }), notObject: m.artifactTrustFailure(null) }),
    claim: "artifact validation names the exact failing field: empty name, missing content, short digest, non-object" },
  { slot: 172, target: TRUST, expected: { emptyWithRealDigest: null, emptyWithOtherDigest: "artifact-digest-mismatch" },
    run: (m) => ({ emptyWithRealDigest: m.artifactTrustFailure({ name: "e", content: "", sha256: sha("") }), emptyWithOtherDigest: m.artifactTrustFailure({ name: "e", content: "", sha256: sha("x") }) }),
    claim: "empty content is trusted only with the genuine empty-string SHA-256 (e3b0c442...)" },
  { slot: 173, target: TRUST, fn: "sha256Hex", input: ["héllo"], expected: sha("héllo"),
    claim: "content is hashed as UTF-8 bytes (checked against an independent node:crypto digest of é as 2 bytes)" },
  { slot: 174, target: DEC, expected: { policy: ["policy-action-denied"], toepara: ["toepara-not-admitted"], trustGate: ["trust-gate-not-authorized"], artifact: ["artifact-digest-mismatch"] },
    run: (m) => ({ policy: m.decide({ ...VALID, action: "x" }).reasons, toepara: m.decide({ ...VALID, toepara: "x" }).reasons, trustGate: m.decide({ ...VALID, trustGate: "x" }).reasons, artifact: m.decide({ ...VALID, artifact: { ...ART, content: "x" } }).reasons }),
    claim: "each single failing stage yields exactly its own one reason (stages do not mask each other)" },
  { slot: 175, target: DEC, expected: ["policy-action-denied", "toepara-not-admitted", "trust-gate-not-authorized", "artifact-name-invalid"],
    run: (m) => m.decide({ action: "merge", toepara: "x", trustGate: "y", artifact: { name: "", content: "c", sha256: "z" } }).reasons,
    claim: "with every stage failing, all four reasons are listed in pipeline order (no short-circuit)" },
  { slot: 176, target: DEC, expected: { action: "detect", toepara: "ADMITTED", trustGate: "AUTHORIZED", artifact: { name: "a.txt", declaredSha256: H, computedSha256: H } },
    run: (m) => m.decide(VALID).evidence, claim: "the receipt carries the exact decision evidence including declared and computed digests" },
  { slot: 177, target: DEC, expected: { computedIsIndependentSha: [true, true, true], declaredEqualsComputedWhenUntampered: [true, true, true], tamperKindsAllDiffer: { edited: true, truncated: true, appended: true } },
    run: (m) => { const contents = ["", "h\u00e9llo \u2713", "x".repeat(5000)]; const ev = (/** @type {any} */ c, over = {}) => m.decide({ ...VALID, artifact: { name: "a.txt", content: c, sha256: sha(c), ...over } }).evidence.artifact; const ok = contents.map((c) => ev(c)); const base = "hello"; const bad = (/** @type {any} */ c) => { const e = ev(c, { sha256: sha(base) }); return e.declaredSha256 !== e.computedSha256; }; return { computedIsIndependentSha: ok.map((e, i) => e.computedSha256 === sha(contents[i])), declaredEqualsComputedWhenUntampered: ok.map((e) => e.declaredSha256 === e.computedSha256), tamperKindsAllDiffer: { edited: bad("hellO"), truncated: bad("hell"), appended: bad("hello!") } }; },
    claim: "for empty, non-ASCII and 5000-char content the receipt's computed digest equals an independent sha256 and the declared one; each of three tamper kinds (edit, truncate, append) makes them differ" },
  { slot: 178, target: DEC, expected: { action: true, toepara: true, trustGate: true, name: true, content: true, sha256: true },
    run: (m) => { const base = m.decide(VALID).inputDigest; return { action: m.decide({ ...VALID, action: "recover" }).inputDigest !== base, toepara: m.decide({ ...VALID, toepara: "x" }).inputDigest !== base, trustGate: m.decide({ ...VALID, trustGate: "x" }).inputDigest !== base, name: m.decide({ ...VALID, artifact: { ...ART, name: "b.txt" } }).inputDigest !== base, content: m.decide({ ...VALID, artifact: { ...ART, content: "hellO" } }).inputDigest !== base, sha256: m.decide({ ...VALID, artifact: { ...ART, sha256: "0".repeat(64) } }).inputDigest !== base }; },
    claim: "changing ANY one of the six decision fields changes the input digest" },
  { slot: 179, target: DEC, expected: { pristine: true, flippedDecision: false, editedReason: false, droppedDigest: false, extraField: false },
    run: (m) => { const r = m.decide(VALID); return { pristine: m.verifyReceipt(r), flippedDecision: m.verifyReceipt({ ...r, decision: "FAIL_CLOSED" }), editedReason: m.verifyReceipt({ ...r, reasons: ["x"] }), droppedDigest: m.verifyReceipt({ ...r, receiptDigest: undefined }), extraField: m.verifyReceipt({ ...r, note: "x" }) }; },
    claim: "verifyReceipt accepts the pristine receipt and rejects a flipped decision, edited reasons, missing digest and an added field" },
  { slot: 180, target: DEC, expected: { equal: true, sealed: true, decision: "FAIL_CLOSED", source: "caller-supplied" },
    run: (m) => { const a = m.malformedInputReceipt("why", "caller-supplied"); const b = m.malformedInputReceipt("why", "caller-supplied"); return { equal: JSON.stringify(a) === JSON.stringify(b), sealed: m.verifyReceipt(a), decision: a.decision, source: a.verdictSource }; },
    claim: "malformed-input receipts are deterministic, sealed (verifyReceipt true) and always FAIL_CLOSED" },
  { slot: 181, target: DEC, fn: "canonicalize", input: [{ b: 1, a: { d: [2, { z: 1, y: 2 }], c: null } }], expected: '{"a":{"c":null,"d":[2,{"y":2,"z":1}]},"b":1}',
    claim: "canonical JSON sorts keys at every depth, including inside arrays" },
  { slot: 182, target: DEC, expected: { undef: "null", fn: "null", str: '"x"' },
    run: (m) => ({ undef: m.canonicalize(undefined), fn: m.canonicalize(() => 1), str: m.canonicalize("x") }), claim: "values JSON cannot represent canonicalize to null instead of throwing or producing 'undefined'" },
  { slot: 183, target: DEC, expected: { nul: false, str: false, num: false, arr: false, empty: false },
    run: (m) => ({ nul: m.verifyReceipt(null), str: m.verifyReceipt("x"), num: m.verifyReceipt(5), arr: m.verifyReceipt([]), empty: m.verifyReceipt({}) }),
    claim: "verifyReceipt is false (never throws) for null, string, number, array and an object with no digest" },
  { slot: 184, target: NORM, expected: { ok: true, frozen: true, artifactFrozen: true, value: { action: "detect", toepara: "ADMITTED", trustGate: "AUTHORIZED", artifact: ART } },
    run: (m) => { const r = m.normalizeInput(VALID); return { ok: r.ok, frozen: Object.isFrozen(r.value), artifactFrozen: Object.isFrozen(r.value.artifact), value: r.value }; },
    claim: "normalization yields a deeply frozen snapshot of exactly the decision fields" },
  { slot: 185, target: NORM, fn: "normalizeInput", input: [new Map([["action", "detect"]])], expected: { ok: false, reason: "input-not-plain-object" }, claim: "a Map instance is not a plain object" },
  { slot: 186, target: NORM, expected: { ok: false, reason: "input-unreadable" },
    run: (m) => m.normalizeInput(new Proxy({}, { getPrototypeOf() { throw new Error("trap"); } })), claim: "a Proxy whose traps throw is reported unreadable, never thrown out of normalize" },
  { slot: 187, target: NORM, expected: { ok: true, value: { action: null, toepara: null, trustGate: null, artifact: { name: null, content: null, sha256: null } } },
    run: (m) => { const r = m.normalizeInput({ action: 5, toepara: true, trustGate: {}, artifact: { name: 1, content: null, sha256: [] } }); return { ok: r.ok, value: r.value }; },
    claim: "every non-string leaf collapses to null so downstream hashing cannot throw" },
  { slot: 188, target: NORM, expected: { ok: false, reason: "input-accessor-property" },
    run: (m) => { const art = { name: "n", content: "c" }; Object.defineProperty(art, "sha256", { enumerable: true, get: () => H }); return m.normalizeInput({ action: "detect", artifact: art }); },
    claim: "an accessor on a nested artifact field is rejected, not read" },
  { slot: 189, target: POL, expected: { detect: true, recover: true, recommend: true, Detect: false, merge: false, deploy: false, num: false, nul: false },
    run: (m) => ({ detect: m.isAllowedAction("detect"), recover: m.isAllowedAction("recover"), recommend: m.isAllowedAction("recommend"), Detect: m.isAllowedAction("Detect"), merge: m.isAllowedAction("merge"), deploy: m.isAllowedAction("deploy"), num: m.isAllowedAction(1), nul: m.isAllowedAction(null) }),
    claim: "the policy predicate allows exactly detect/recover/recommend, case-sensitively" },
  { slot: 190, target: POL, expected: { list: ["detect", "recover", "recommend"], predicateAgreesWithList: true, dangerousVerbsInList: [] },
    run: (m) => { const list = [...m.ALLOWED_ACTIONS]; const dangerous = ["merge", "deploy", "authorize", "approve", "push", "delete", "admit", "release", "force-push"]; const universe = [...list, ...dangerous, "", "DETECT", " detect"]; return { list, predicateAgreesWithList: universe.every((v) => list.includes(v) === m.isAllowedAction(v)), dangerousVerbsInList: dangerous.filter((v) => list.includes(v)) }; },
    claim: "the exported allow-list is exactly [detect, recover, recommend], contains none of nine dangerous verbs, and the predicate agrees with the list over the whole universe (no hidden second rule)" },
  { slot: 191, target: ADP, expected: { decision: "PROCEED", verdictSource: "adapter", reasons: [] },
    run: (m) => { const r = m.decideWithAdapters({ action: "detect", artifact: ART }, GOOD); return { decision: r.decision, verdictSource: r.verdictSource, reasons: r.reasons }; },
    claim: "when both adapters return the exact verdicts the pipeline proceeds and records source 'adapter'" },
  { slot: 192, target: ADP, expected: { decision: "FAIL_CLOSED", reasons: ["toepara-not-admitted", "trust-gate-not-authorized"] },
    run: (m) => brief(m.decideWithAdapters(VALID, { toepara: ADM("REJECTED"), trustGate: ADM("DENIED") })),
    claim: "caller-typed ADMITTED/AUTHORIZED are ignored in adapter mode: the adapters' REJECTED/DENIED decide" },
  { slot: 193, target: ADP, expected: { seenToepara: null, seenTrustGate: null, seenArtifact: "a.txt" },
    run: (m) => { let seen = /** @type {any} */ (null); m.decideWithAdapters(VALID, { toepara: { name: "t", verdict: (/** @type {any} */ e) => { seen = e; return "ADMITTED"; } }, trustGate: ADM("AUTHORIZED") }); return { seenToepara: seen.toepara, seenTrustGate: seen.trustGate, seenArtifact: seen.artifact.name }; },
    claim: "adapters receive the artifact but never the caller's own verdict fields" },
  { slot: 194, target: ADP, expected: { decision: "FAIL_CLOSED", reasons: ["toepara-not-admitted"], threw: false },
    run: (m) => { let threw = false; let r; try { r = m.decideWithAdapters(VALID, { toepara: { name: "t", verdict: () => { throw new Error("down"); } }, trustGate: ADM("AUTHORIZED") }); } catch { threw = true; } return { ...brief(r), threw }; },
    claim: "an adapter that throws means no verdict: fail closed with the toepara reason and no exception" },
  { slot: 195, target: ADP, expected: { control: "PROCEED", promise: "FAIL_CLOSED", boxed: "FAIL_CLOSED", number: "FAIL_CLOSED" },
    run: (m) => { const d = (/** @type {any} */ v) => m.decideWithAdapters({ action: "detect", artifact: ART }, { toepara: GOOD.toepara, trustGate: ADM(v) }).decision; return { control: d("AUTHORIZED"), promise: d(Promise.resolve("AUTHORIZED")), boxed: d(new String("AUTHORIZED")), number: d(1) }; },
    claim: "a Promise, boxed String or number from the trust gate is not a verdict (control with the exact string proceeds)" },
  { slot: 196, target: ADP, expected: { decision: "FAIL_CLOSED", reasons: ["toepara-not-admitted", "trust-gate-not-authorized"] },
    run: (m) => brief(m.decideWithAdapters({ action: "detect", artifact: ART }, undefined)), claim: "omitting the adapters entirely fails closed rather than skipping both gates" },
  { slot: 197, target: ADP, expected: { policy: ["policy-action-denied"], tamper: ["artifact-digest-mismatch"] },
    run: (m) => ({ policy: m.decideWithAdapters({ action: "deploy", artifact: ART }, GOOD).reasons, tamper: m.decideWithAdapters({ action: "detect", artifact: { ...ART, content: "x" } }, GOOD).reasons }),
    claim: "policy and artifact trust still apply in adapter mode even with unanimous adapters" },
  { slot: 198, target: ADP, expected: { sameInputDigestAsDecide: true, receiptDigestDiffers: true },
    run: async (m) => { const { decide } = await import("../../../cerberus/core/decide.ts"); const a = m.decideWithAdapters({ action: "detect", artifact: ART }, GOOD); const b = decide(VALID); return { sameInputDigestAsDecide: a.inputDigest === b.inputDigest, receiptDigestDiffers: a.receiptDigest !== b.receiptDigest }; },
    claim: "adapter mode decides on the same snapshot as decide() (equal inputDigest) but records a different verdict source (different receiptDigest)" },
  { slot: 199, target: ADP, expected: { names: ["stub:t", "stub:g"], ignoresEvidence: true, bothFixedRight: { decision: "PROCEED", reasons: [] }, swapped: { decision: "FAIL_CLOSED", reasons: ["toepara-not-admitted", "trust-gate-not-authorized"] } },
    run: (m) => { const t = m.stubAdapter("t", "ADMITTED"); const g = m.stubAdapter("g", "AUTHORIZED"); const brief2 = (/** @type {any} */ r) => ({ decision: r.decision, reasons: r.reasons }); return { names: [t.name, g.name], ignoresEvidence: t.verdict({ a: 1 }) === t.verdict({ b: 2 }), bothFixedRight: brief2(m.decideWithAdapters({ action: "detect", artifact: ART }, { toepara: t, trustGate: g })), swapped: brief2(m.decideWithAdapters({ action: "detect", artifact: ART }, { toepara: m.stubAdapter("x", "AUTHORIZED"), trustGate: m.stubAdapter("y", "ADMITTED") })) }; },
    claim: "stub adapters are visibly named stub:<name>, return their fixed verdict whatever the evidence, and drive decideWithAdapters: right verdicts PROCEED, swapped verdicts fail closed on both gates" },
  { slot: 200, target: DEC, expected: { inputDigest: sha('{"malformed":"r"}'), reasons: ["r"], decision: "FAIL_CLOSED", input: "FAIL", rest: ["NOT_EVALUATED", "NOT_EVALUATED", "NOT_EVALUATED", "NOT_EVALUATED"] },
    run: (m) => { const r = m.malformedInputReceipt("r", "adapter"); return { inputDigest: r.inputDigest, reasons: r.reasons, decision: r.decision, input: r.stages.input, rest: [r.stages.policy, r.stages.toepara, r.stages.trustGate, r.stages.artifactTrust] }; },
    claim: "a malformed-input receipt digests canonical {malformed:reason} (independent sha256 literal) and marks later stages NOT_EVALUATED" },
];
